"""topic tables

Revision ID: 6d4190a6ca34
Revises: 3c0627027265
Create Date: 2026-05-31 23:55:13.387829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d4190a6ca34'
down_revision: Union[str, Sequence[str], None] = '3c0627027265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rb_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_rb_topic_name'), 'rb_topic', ['name'], unique=True)
    op.create_table('post_topic_link',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['rb_topic.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_topic_link')
    op.drop_index(op.f('ix_rb_topic_name'), table_name='rb_topic')
    op.drop_table('rb_topic')
    # ### end Alembic commands ###
